### PR TITLE
Test allied telesis

### PR DESCRIPTION
**Pull request by tatumi0726**
Hello!

We have created each file for Allied-Telesis and have even completed testing.

We would appreciate your confirmation that it is merge-worthy.
Please let us know if any corrections are necessary.
Thank you in advance for your time.

### CODE REVIEW

**Comment by dainok** [comment]
@tatumi0726 question: I see no commands about VRF. Is VRF not supported or just not included in your scripts?

**Comment by dainok** [comment]
@tatumi0726 second question: for each command I need the minimum alias, if exists.
For example:
- show arp -> sh ar
- show system -> show sys
- ...
Thank you

**Comment by tatumi0726** [comment]
Hello, @dainok

Sorry for the late reply.

I have written VRF in Ingestor to collect from the logs obtained by "show
ip route".
Should I re-create it?

I think it is possible to get it by "show ip route vrf <name>".

I will answer with the alias of each command.
show arp -> sh ar
show etherchannel summary -> sh et s
show interface -> sh in
show interface switchport -> sh in s
show ip interface -> sh ip in
show_lldp_neighbors_detail -> sh ll n d
show_mac_address_table -> sh mac a
show_static_channel_group -> sh stat
show system -> sh sy
show_vlan_all -> sh vl al

Please contact us if there is any other information you need to provide.
Thank you in advance.

2024年2月12日(月) 2:01 Andrea Dainese ***@***.***>:

**Comment by dainok** [comment]
Hi @tatumi0726 

VRF: ok sorry I didn't realize that.
Aliases: I need also the alias for "show ip route"

Next steps:
1. I need to complete the PR for templates. I'm adding some requirements from NTS like error management and field normalization.
2. Once the PR is completed, I'll ask you to check it on your production systems. That's because NTC it's not maintained by me and I prefer to commit only when I'm sure that everything is working
3. Once the templates are released I'll check netdoc code.

**Comment by tatumi0726** [comment]
Hello, @dainok

My apologies...I will contact you as follows

show ip route -> sh ip ro

All of this was confirmed using the actual device.

I understand about the next steps.
I will implement what I can and look forward to hearing from you!

Thank you very much in advance.

2024年2月12日(月) 17:48 Andrea Dainese ***@***.***>:

**Comment by dainok** [comment]
@tatumi0726 any way to get VRF info in "show ip interface"?
"show ip interface" includes IP from any VRF?

**Comment by dainok** [comment]
@tatumi0726 I see in show static-channel-group that 2 different outputs are possible.
I need an example from `OldSA`

**Comment by tatumi0726** [comment]
Good evening, @dainok.

The "show ip interface" did not output VRF information.
I believe the command that would output the information you wanted would be
'show ip vrf interface'

Example output:
awplus> show ip vrf interface ↓
Interface IP-Address Status Protocol Vrf
lo1 unassigned admin up running red
lo2 unassigned admin up running green
vlan1 192.168.10.1/24 admin up running red
vlan2 192.168.20.1/24 admin up running green


Regarding the example output of show static-channel-group.
During the creation of this file, I forgot to separate it once because
there were differences in the command output on slightly older firmware.
The following is an example output.

Example output:
awplus> show static-channel-group ↓
% Static Aggregator: sa11
% Member: sa1
   port1.1.1
   port1.1.2
   port1.1.3
   port1.1.4

Thank you for your time...

**Comment by dainok** [comment]
Hi @tatumi0726 
❗️ I almost completed templates. VRF/routing is missing, but I need more time to think about.
In the meanwhile please double check the template I adjusted. Templates will be the fundamental part to parse data. You are required to check templates on your production environment:

Here the templates: https://github.com/dainok/ntc-templates/tree/add_allied_telesis/ntc_templates/templates
Here I test I developed: https://github.com/dainok/ntc-templates/tree/add_allied_telesis/tests/allied_telesis_awplus

Notify my each exception and attach an output file so I can improve templates and tests.

**Comment by tatumi0726** [comment]
Hi, @dainok!

Thanks for your reply.
I am very sorry for your busy schedule and for the maintenance of the
template.

I understand about the template file confirmation.

I will check it this Friday or Saturday and report back to you.

2024年2月13日(火) 23:30 Andrea Dainese ***@***.***>:

**Comment by dainok** [comment]
Moved to https://github.com/dainok/netdoc/pull/122

**Pull request closed without merging**
